Improve containerd CI with PowerVS

diff --git a/config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml b/config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml
--- a/config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml
+++ b/config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml
@@ -30,9 +30,6 @@ periodics:
               set -o nounset
               set -o pipefail
               set -o xtrace
-              export KUBE_TIMEOUT='--timeout=600s'
-              export KUBE_KEEP_VERBOSE_TEST_OUTPUT=y
-              export LOG_LEVEL=4
 
               # Connect to IBMCloud
               echo "" | ibmcloud login
@@ -41,21 +38,33 @@ periodics:
 
               wget https://raw.githubusercontent.com/ppc64le-cloud/docker-ce-build/main/test-containerd/instanciate_powervs_vm.sh
               chmod +x instanciate_powervs_vm.sh
+
               # Run test server in parallel
               # sleep is needed to avoid trouble with ibmcloud
-              bash -x ./instanciate_powervs_vm.sh --output ${ARTIFACTS} --name rdr-runtimes-dev-etienne_guesnet-runc_l1 --runc runc --runtime "io.containerd.runtime.v1.linux" --key atos-key --network  'public-192_168_141_8-29-VLAN_2093' &
+              mkdir ${ARTIFACTS}/runc_l1/
+              bash -x ./instanciate_powervs_vm.sh --output ${ARTIFACTS}/runc_l1/ --name rdr-runtimes-dev-etienne_guesnet-runc-l1 --runc runc --runtime "io.containerd.runtime.v1.linux" --key atos-key --network  'public-192_168_141_8-29-VLAN_2093' 2>&1 | tee runc_l1.txt &
               sleep 300
-              bash -x ./instanciate_powervs_vm.sh --output ${ARTIFACTS} --name rdr-runtimes-dev-etienne_guesnet-runc_v1 --runc runc --runtime "io.containerd.runc.v1" --key atos-key --network 'public-192_168_141_8-29-VLAN_2093' &
+              mkdir ${ARTIFACTS}/runc_v1/
+              bash -x ./instanciate_powervs_vm.sh --output ${ARTIFACTS}/runc_v1/ --name rdr-runtimes-dev-etienne_guesnet-runc-v1 --runc runc --runtime "io.containerd.runc.v1" --key atos-key --network 'public-192_168_141_8-29-VLAN_2093' 2>&1 | tee runc_v1.txt &
               sleep 300
-              bash -x ./instanciate_powervs_vm.sh --output ${ARTIFACTS} --name rdr-runtimes-dev-etienne_guesnet-runc_v2 --runc runc --runtime "io.containerd.runc.v2" --key atos-key --network 'public-192_168_141_8-29-VLAN_2093' &
+              mkdir ${ARTIFACTS}/runc_v2/
+              bash -x ./instanciate_powervs_vm.sh --output ${ARTIFACTS}/runc_v2/ --name rdr-runtimes-dev-etienne_guesnet-runc-v2 --runc runc --runtime "io.containerd.runc.v2" --key atos-key --network 'public-192_168_141_8-29-VLAN_2093' 2>&1 | tee runc_v2.txt &
               sleep 300
-              bash -x ./instanciate_powervs_vm.sh --output ${ARTIFACTS} --name rdr-runtimes-dev-etienne_guesnet-crun_v2 --runc crun --runtime "io.containerd.runc.v2" --key atos-key --network 'public-192_168_141_8-29-VLAN_2093' &
+              mkdir ${ARTIFACTS}/crun_v2/
+              bash -x ./instanciate_powervs_vm.sh --output ${ARTIFACTS}/crun_v2/ --name rdr-runtimes-dev-etienne_guesnet-crun-v2 --runc crun --runtime "io.containerd.runc.v2" --key atos-key --network 'public-192_168_141_8-29-VLAN_2093' 2>&1 | tee crun_v2.txt &
 
               # Wait until all jobs are completed
               while [ -n "`jobs -r`" ]; do
                 sleep 60
               done
-              echo "Done"
+
+              # Check results
+              grep -En "FAIL:|FAILED" *.txt
+              if [ "$?" == "0" ]; then
+                  echo "Failures found"
+                  exit 1
+              fi
+              echo "Done without failure"
           env:
             - name: IBMCLOUD_API_KEY
               valueFrom:
